"""init

Revision ID: 1a8628be7547
Revises: b284a90e0082
Create Date: 2021-11-19 17:01:24.577696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8628be7547'
down_revision = 'b284a90e0082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant', sa.Column('test_choice', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant', 'test_choice')
    # ### end Alembic commands ###
