"""init

Revision ID: b284a90e0082
Revises: e4d536d57838
Create Date: 2021-11-05 11:42:07.458614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b284a90e0082'
down_revision = 'e4d536d57838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant', 'avatar',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True,
               existing_comment='用户头像')
    op.alter_column('merchant', 'no',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True,
               existing_comment='工号')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant', 'no',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False,
               existing_comment='工号')
    op.alter_column('merchant', 'avatar',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False,
               existing_comment='用户头像')
    # ### end Alembic commands ###
