"""init

Revision ID: b6f12253eb7d
Revises: c544ee6b545e
Create Date: 2021-10-28 17:19:35.883007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6f12253eb7d'
down_revision = 'c544ee6b545e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_time', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True, verbose_name='创建时间'))
    op.add_column('user', sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, verbose_name='更新时间'))
    op.add_column('user', sa.Column('nickname', sa.String(length=32), nullable=False, verbose_name='昵称(用于登录)'))
    op.add_column('user', sa.Column('realname', sa.String(length=32), nullable=False, verbose_name='真实姓名'))
    op.add_column('user', sa.Column('phone', sa.String(length=18), nullable=False, verbose_name='手机号(用于登录)'))
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=False, verbose_name='用于密码'))
    op.add_column('user', sa.Column('avatar', sa.String(length=256), nullable=False, verbose_name='用户头像'))
    op.add_column('user', sa.Column('state', sa.Boolean(), nullable=True, verbose_name='账户状态'))
    op.add_column('user', sa.Column('group', sa.BigInteger(), nullable=False, verbose_name='用户组'))
    op.add_column('user', sa.Column('extra_field1', sa.String(length=256), nullable=True, verbose_name='冗余字段1'))
    op.add_column('user', sa.Column('extra_field2', sa.String(length=256), nullable=True, verbose_name='冗余字段2'))
    op.add_column('user', sa.Column('extra_field3', sa.String(length=256), nullable=True, verbose_name='冗余字段3'))
    op.add_column('user', sa.Column('extra_field4', sa.String(length=256), nullable=True, verbose_name='冗余字段4'))
    op.drop_column('user', 'age')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('user', sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user', 'extra_field4')
    op.drop_column('user', 'extra_field3')
    op.drop_column('user', 'extra_field2')
    op.drop_column('user', 'extra_field1')
    op.drop_column('user', 'group')
    op.drop_column('user', 'state')
    op.drop_column('user', 'avatar')
    op.drop_column('user', 'password')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'realname')
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'update_time')
    op.drop_column('user', 'create_time')
    # ### end Alembic commands ###
