"""init

Revision ID: d28bd535b6d4
Revises: 3bd04ae1b323
Create Date: 2021-11-01 14:32:47.729484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd28bd535b6d4'
down_revision = '3bd04ae1b323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('p_name', sa.String(length=32), nullable=True, comment='权限名称'),
    sa.Column('P_code', sa.String(length=32), nullable=True, comment='权限代码'),
    sa.Column('uri', sa.String(length=128), nullable=True, comment='权限对应的uri'),
    sa.Column('method', sa.String(length=12), nullable=True, comment='uri对应的方法'),
    sa.Column('p_desc', sa.String(length=256), server_default='', nullable=True, comment='权限描述'),
    sa.Column('p_state', sa.Boolean(), nullable=True, comment='权限状态'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('P_code'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('p_name'),
    sa.UniqueConstraint('uri', 'method', name='ix_uri_method')
    )
    op.drop_table('admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aex', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('permission')
    # ### end Alembic commands ###
